name: score
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.5.0=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - backports.zoneinfo=0.2.1=py38h294d835_4
  - black=22.1.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h294d835_1003
  - ca-certificates=2021.10.8=h5b45459_0
  - cffi=1.15.0=py38hd8c33c5_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.0.3=py38haa244fe_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py38h21b164f_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py38h885f38d_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dj-rest-auth=2.2.4=pyhd8ed1ab_0
  - django=4.0.3=py38haa244fe_0
  - django-allauth=0.41.0=py_0
  - djangorestframework=3.13.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.2=pyhd8ed1ab_0
  - fire=0.4.0=pyh44b312d_0
  - idna=3.3=pyhd8ed1ab_0
  - ipykernel=6.9.0=py38h595d716_0
  - ipython=8.0.1=py38haa244fe_0
  - jedi=0.18.1=py38haa244fe_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38haa244fe_1
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mypy_extensions=0.4.3=py38haa244fe_4
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openssl=3.0.2=h8ffe710_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=22.0.3=pyhd8ed1ab_0
  - platformdirs=2.5.0=pyhd8ed1ab_0
  - plotly=5.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.27=pyha770c72_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py38haa244fe_4
  - python=3.8.12=h900ac77_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2022.1=pyhd8ed1ab_0
  - python3-openid=3.2.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyzmq=22.3.0=py38h09162b1_1
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - setuptools=60.9.1=py38haa244fe_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h8ffe710_0
  - sqlparse=0.4.2=pyhd8ed1ab_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.1=py38h294d835_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.2=py38h294d835_0
  - typing_extensions=4.1.1=pyha770c72_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py38haa244fe_3
  - zeromq=4.3.4=h0e60522_1
  - pip:
    - aenum==3.1.8
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==21.4.0
    - beautifulsoup4==4.10.0
    - blis==0.7.6
    - cachetools==4.2.4
    - catalogue==2.0.6
    - certifi==2021.10.8
    - click-params==0.1.2
    - cloudpickle==2.0.0
    - cloup==0.8.2
    - cycler==0.11.0
    - cymem==2.0.6
    - dask==2022.2.0
    - dateparser==1.1.0
    - deprecated==1.2.13
    - deprecation==2.1.0
    - diskcache==5.4.0
    - distributed==2022.2.0
    - environs==9.5.0
    - fastai==2.5.3
    - fastcore==1.3.27
    - fastdownload==0.0.5
    - fastprogress==1.0.2
    - fonttools==4.29.1
    - frozenlist==1.3.0
    - fsspec==2021.7.0
    - heapdict==1.0.1
    - imbalanced-learn==0.9.0
    - importlib-resources==5.4.0
    - ipython-genutils==0.2.0
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - kiwisolver==1.3.2
    - langcodes==3.3.0
    - llvmlite==0.37.0
    - locket==0.2.1
    - lxml==4.7.1
    - markupsafe==2.0.1
    - marshmallow==3.14.1
    - matplotlib==3.5.1
    - matrixprofile==1.1.10
    - measurement==3.2.0
    - mpmath==1.2.1
    - msgpack==1.0.3
    - multidict==6.0.2
    - murmurhash==1.0.6
    - nbformat==5.1.3
    - numba==0.54.1
    - numpy==1.19.3
    - packaging==21.3
    - pandas==1.4.1
    - partd==1.2.0
    - pathy==0.6.1
    - patsy==0.5.2
    - pillow==9.0.1
    - pint==0.17
    - preshed==3.0.6
    - protobuf==3.11.2
    - psutil==5.9.0
    - pydantic==1.8.2
    - pyparsing==3.0.7
    - pypdf2==1.26.0
    - pyrsistent==0.18.1
    - python-dotenv==0.19.2
    - pyts==0.12.0
    - pytz==2021.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.2.0
    - pywin32==303
    - pyyaml==6.0
    - rapidfuzz==1.9.1
    - regex==2022.1.18
    - requests-ftp==0.3.1
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - sktime==0.9.0
    - smart-open==5.2.1
    - sortedcontainers==2.4.0
    - soupsieve==2.3.1
    - spacy==3.2.2
    - spacy-legacy==3.0.8
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - statsmodels==0.12.1
    - stumpy==1.10.2
    - sympy==1.9
    - tabulate==0.8.9
    - tblib==1.7.0
    - thinc==8.0.13
    - threadpoolctl==3.1.0
    - timezonefinder==5.2.0
    - toolz==0.11.2
    - torch==1.10.2
    - torchvision==0.11.3
    - tqdm==4.62.3
    - tsai==0.2.25
    - tsfresh==0.18.0
    - typer==0.4.0
    - tzdata==2021.5
    - tzlocal==4.1
    - urllib3==1.26.8
    - validators==0.18.2
    - wasabi==0.9.0
    - wetterdienst==0.26.0
    - wrapt==1.13.3
    - yarl==1.7.2
    - zict==2.0.0
    - zipp==3.7.0
prefix: C:\Users\Marian\anaconda3\envs\score
