name: solar
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8=h5b45459_0
  - openssl=3.0.0=h8ffe710_2
  - pip=22.0.3=pyhd8ed1ab_0
  - python=3.8.12=h900ac77_2_cpython
  - python_abi=3.8=2_cp38
  - setuptools=60.7.1=py38haa244fe_0
  - sqlite=3.37.0=h8ffe710_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wheel=0.37.1=pyhd8ed1ab_0
  - pip:
    - aenum==3.1.8
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==21.4.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.10.0
    - blis==0.7.5
    - cachetools==4.2.4
    - catalogue==2.0.6
    - certifi==2021.10.8
    - charset-normalizer==2.0.11
    - click==8.0.3
    - click-params==0.1.2
    - cloudpickle==2.0.0
    - cloup==0.8.2
    - colorama==0.4.4
    - cycler==0.11.0
    - cymem==2.0.6
    - dask==2022.1.1
    - dateparser==1.1.0
    - decorator==5.1.1
    - deprecated==1.2.13
    - deprecation==2.1.0
    - diskcache==5.4.0
    - distributed==2022.1.1
    - fastai==2.5.3
    - fastcore==1.3.27
    - fastdownload==0.0.5
    - fastprogress==1.0.0
    - fonttools==4.29.1
    - frozenlist==1.3.0
    - fsspec==2021.7.0
    - heapdict==1.0.1
    - idna==3.3
    - imbalanced-learn==0.9.0
    - importlib-resources==5.4.0
    - ipython-genutils==0.2.0
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter-core==4.9.1
    - kiwisolver==1.3.2
    - langcodes==3.3.0
    - llvmlite==0.38.0
    - locket==0.2.1
    - lxml==4.7.1
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - matrixprofile==1.1.10
    - measurement==3.2.0
    - mpmath==1.2.1
    - msgpack==1.0.3
    - multidict==6.0.2
    - murmurhash==1.0.6
    - nbformat==5.1.3
    - numba==0.55.1
    - numpy==1.21.5
    - packaging==21.3
    - pandas==1.4.0
    - partd==1.2.0
    - pathy==0.6.1
    - patsy==0.5.2
    - pillow==9.0.1
    - pint==0.17
    - preshed==3.0.6
    - protobuf==3.11.2
    - psutil==5.9.0
    - pydantic==1.8.2
    - pyparsing==3.0.7
    - pypdf2==1.26.0
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pyts==0.12.0
    - pytz==2021.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.2.0
    - pywin32==303
    - pyyaml==6.0
    - rapidfuzz==1.9.1
    - regex==2022.1.18
    - requests==2.27.1
    - requests-ftp==0.3.1
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - six==1.16.0
    - sktime==0.10.0
    - smart-open==5.2.1
    - sortedcontainers==2.4.0
    - soupsieve==2.3.1
    - spacy==3.2.1
    - spacy-legacy==3.0.8
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - statsmodels==0.13.1
    - stumpy==1.10.2
    - sympy==1.9
    - tabulate==0.8.9
    - tblib==1.7.0
    - thinc==8.0.13
    - threadpoolctl==3.1.0
    - timezonefinder==5.2.0
    - toolz==0.11.2
    - torch==1.10.2
    - torchvision==0.11.3
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.1
    - tsai==0.2.24
    - tsfresh==0.19.0
    - typer==0.4.0
    - typing-extensions==4.0.1
    - tzdata==2021.5
    - tzlocal==4.1
    - urllib3==1.26.8
    - validators==0.18.2
    - wasabi==0.9.0
    - wetterdienst==0.25.1
    - wrapt==1.13.3
    - yarl==1.7.2
    - zict==2.0.0
    - zipp==3.7.0
prefix: C:\Users\Marian\anaconda3\envs\solar
